language: emacs-lisp
before_install:
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
    sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq
        emacs-snapshot-el emacs-snapshot-nox;
    fi
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg;
    fi
  - curl -fsSkL https://raw.github.com/rejeep/cask.el/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask
  - $EMACS --version
env:
  - EMACS=emacs24
script:
  - cask exec ecukes
