(defvar shared-lisp-dir (expand-file-name "~/.emacs.d/lib"))

(add-to-list 'load-path shared-lisp-dir)
(add-to-list 'load-path "~/.emacs.d/config/")
(add-to-list 'load-path "~/.emacs.d/lib/yasnippet")
(add-to-list 'load-path "~/.emacs.d/lib/expand-region")
(add-to-list 'load-path "~/.emacs.d/lib/jabber")
(add-to-list 'load-path "~/.emacs.d/lib/magit")

(require 'gist)
(require 'magit)
(require 'vc-svn17)
(require 'key-chord)
(require 'iy-go-to-char)
(require 'ace-jump-mode)
(require 'browse-kill-ring)
(require 'keymaps)
(require 'mark-multiple)
(require 'inline-string-rectangle)
(require 'mark-more-like-this)
(require 'jabber)
(require 'modes)
(require 'restclient)
(require 'json-reformat)
(require 'expand-region)
(require 'uniquify)
(require 'yasnippet)
(yas/global-mode 1)

(require 'aesthetics-config)
(require 'modeline-config)
(require 'saveplace-config)
(require 'uniquify-config)
(require 'ido-config)
(require 'misc-config)